config/routes.rb
Rails.application.routes.draw do

  get 'search/create'

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users

  resources :pictures do
      resources :comments, only: [:create,:destroy]
      member do
        put "like", to: "pictures#like"
        put "dislike", to: "pictures#unlike"
    end
  end

  #root 'pictures#index'

  resources :users, only: [:show,:index]

  devise_scope :user do
      get "sign_out", :to => 'devise/sessions#destroy'
      get "sign_in", :to => "devise/sessions#new"
      authenticated :user do
        root :to => 'pictures#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/sessions#new', as: :unauthenticated_root
      end
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :picture
    belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base

    has_attached_file :image, styles: {medium: "600x", preview:"291x291^", thumb: "100x100>" }, default_url: "pinterest-pin.png"
		validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)

    validates :image, presence: true

    include SimpleHashtag::Hashtaggable
    hashtaggable_attribute :description

    belongs_to :user
    has_many :comments, dependent: :destroy

    acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_attached_file :avatar, styles: { medium: "250x", thumb: "100x100>", mini: "30x30>" }, default_url: "pinterest-pin.png"
     validates_attachment_content_type :avatar, content_type: %w(image/jpeg image/jpg image/png)

 validates :avatar, presence: true
 validates :name, presence: true
 validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:sign_up) << :slug
    devise_parameter_sanitizer.for(:sign_up) << :bio
    devise_parameter_sanitizer.for(:sign_up) << :webpage

    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :username
    devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :slug
    devise_parameter_sanitizer.for(:account_update) << :bio
    devise_parameter_sanitizer.for(:account_update) << :webpage

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_pic

    def create
        @comment = @picture.comments.build(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            respond_to do |format|
                format.html { redirect_to :back, notice: "Commented succesfully." }
                format.js
              end
        else
            redirect_to :back, alert: "Error: try again."
        end
    end

    def destroy
      @comment = @picture.comments.find(params[:id])

        if @comment.user_id == current_user.id
          @comment.delete
          respond_to do |format|
            format.html { redirect_to :back, notice: "Comment deleted succesfully." }
            format.js
          end
        end

    end

    private

    def comment_params
        params.require(:comment).permit(:content)
    end

    def set_pic
        @picture = Picture.find(params[:picture_id])
    end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
    @hashtags = SimpleHashtag::Hashtag.all
  end

  def show
    @hashtag = SimpleHashtag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def index
      @pictures = Picture.all.order('created_at DESC')
  end

  def new
      @picture = Picture.new
  end

  def create
      @picture = Picture.new picture_params
      @picture.user_id = current_user.id

      if @picture.save
          redirect_to @picture, notice: "Pic uploaded succesfully."
      else
          render 'new', alert: "Error: try again."
      end
  end

  def show
      @picture = Picture.find(params[:id])

  end

  def edit
      @picture = Picture.find(params[:id])
  end

  def update
      @picture = Picture.find(params[:id])

      respond_to do |f|
			if @picture.update(picture_params)
				f.html {redirect_to @picture, notice: "Pic updated succesfully."}
				f.json { render :show, status: :ok, location: @picture }
			else
				f.html { render :edit }
				f.json { render json: @picture.errors, status: :unprocessable_entity }
			end
		end
  end

  def destroy
      @picture = Picture.find(params[:id])
      @picture.destroy

      redirect_to pictures
  end

  def like
    @picture = Picture.find(params[:id])
    @picture.liked_by current_user

    redirect_to :back

 end

 def unlike
    @picture = Picture.find(params[:id])
    @picture.unliked_by current_user

    redirect_to :back
 end

  private

  def picture_params
      params.require(:picture).permit(:description,:image,:user_id)
  end

  def check_user
      @picture = Picture.find(params[:id])
    	if current_user != @picture.user
    		redirect_to root, alert: "This pic is not yours"
    	end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
      word = "%#{params[:keyword]}%"

      @users = User.where("username LIKE ? OR name LIKE ?",word,word)
      @tags = SimpleHashtag::Hashtag.where("name LIKE ?",word)

      respond_to do |format|
          format.html { redirect_to :back }
          format.js 
      end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all.order('username ASC')
  end

  def show
      @user = User.friendly.find(params[:id])
      @pictures = @user.pictures
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def linkify_hashtags(hashtaggable_content)
    regex = SimpleHashtag::Hashtag::HASHTAG_REGEX
    hashtagged_content = hashtaggable_content.to_s.gsub(regex) do
      link_to($&, hashtag_path($2), {class: :hashtag})
    end
    hashtagged_content.html_safe
  end

  def render_hashtaggable(hashtaggable)
    klass        = hashtaggable.class.to_s.underscore
    view_dirname = klass.pluralize
    partial      = klass
    render "#{view_dirname}/#{partial}", {klass.to_sym => hashtaggable}
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
    <%= link_to comment.user.username, comment.user %> <%= comment.content %>
    <% if comment.user == current_user %>
        <%= link_to picture_comment_path(picture,comment), method: :delete, data: { confirm: "Are you sure?" }, :class => "delete-comment", remote: true do %>
            <i class="fa fa-times"></i>
        <% end %>
    <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @picture.id %>').append("<%= j render 'comments/comment', picture: @picture, comment: @comment %>");
$('#comment_content_<%= @picture.id %>').val('');

app/views/comments/destroy.js.erb
$('#comments_<%= @picture.id %>').html("<%= j render @picture.comments, picture: @picture, comment: @comment %>");

app/views/hashtags/index.html.erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %></li>
<% end -%>
</ul>

app/views/hashtags/show.html.erb
<h1><%= params[:hashtag] %></h1>
<% if @hashtagged %>
  <% @hashtagged.each do |hashtagged| %>
    <%= render_hashtaggable hashtagged %>
  <% end -%>
<% else -%>
  <p>There is no match for the <em><%= params[:hashtag] %></em> hashtag.</p>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instapic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Raleway:700,400,200' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
</head>
<body>
    <% if controller.action_name != 'new' %>
    <nav class="navbar">
        <% if controller.action_name == 'index' %>
        <div class="super_skinny_wrapper">
        <% else %>
        <div class="wrapper2">
        <% end %>
            <div class="navbar-brand col-md-4 col-sm-4">
                <%= link_to "Instapic", authenticated_root_path %>
            </div>
            <% if user_signed_in? %>
            <div class="search-form col-md-4 col-sm-4">
                <%= form_tag "/search/create", method: :get, id: "search_form" do %>
                  <div class="fieldContainer">
                      <span class="fa fa-search"></span>

                        <%= text_field_tag :keyword, nil, placeholder: "Search", id: "query", class: "searchField blur" %>

                      <!-- <input type="search" id="query" class="searchField blur" placeholder="Search"> -->
                  </div>
                   <% end %>
                   <div class="searching_results"></div>
            </div>
            <div class="user col-md-4 col-sm-4">
                <% if controller.controller_name == 'users' && controller.action_name == 'show' %>
                    <% if @user == current_user %>
                        <%= link_to "Sign out",destroy_user_session_path, method: :delete %>
                    <% else %>
                        <%= link_to "#{current_user.username}",current_user %>
                    <% end %>
                <% else %>
                <%= link_to "#{current_user.username}",current_user %>
                <% end %>
            </div>
            <% end %>
        </div>
    </nav>
    <% end %>
    <% if notice %>
          <div class="alert alert-success">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <ul>
              <li>
                <%= notice %>
              </li>
            </ul>
          </div>
    <% elsif alert %>
        <div class="alert alert-danger">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <ul>
            <li>
              <%= alert %>
            </li>
          </ul>
        </div>
    <% end %>

<%= yield %>

<% if user_signed_in? %>
    <a href="/pictures/new">
        <div class="new_pic">
            <i class="fa fa-camera-retro"></i>
        </div>
    </a>
    <div class="tooltip_new_pic">
        <p>
            New picture
        </p>
    </div>
<% end %>


</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
    <% if @picture.errors.any? %>

        <h2><%= pluralize(@picture.errors.count, "error") %> prevented from saving the pic:</h2>
        <ul>
            <% @picture.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>

    <% end %>

    <div class="form-group">
		<%= f.label :pic %><br>
    	<%= f.file_field :image, class: "form-control" %> <br>
    </div>
	<div class="form-group">
		<%= f.label :description %> <br>
		<%= f.text_area :description, class: "form-control" %>
	</div>
	<div class="form-group">
   	 	<%= f.submit "Submit", class: "btn btn-success" %>
 	</div>


<% end %>
<div class="cancel_btn">
    <%= link_to "Cancel", authenticated_root_path, class: "btn btn-danger" %>
</div>

app/views/pictures/_pic.html.erb
<div class="picture">
    <%= image_tag @picture.image.url(:medium), :class => "imageShow" %>
    <div id="allBoutImage" class="all">
        <div class="user">
            <%= link_to (image_tag(@picture.user.avatar.url(:mini),:class => "img-circle") + " #{@picture.user.username}"), @picture.user %>
        </div>
        <div class="likes">
            <div class="count">
                <%= @picture.get_likes.size %> likes
            </div>
            <div class="time">
                <%= time_ago_in_words(@picture.created_at) %>
            </div>
        </div>
        <div class="desc_comments">
            <div class="description">
                <%= link_to @picture.user.username, @picture.user %> <%= @picture.description %>
            </div>
            <div class="comments" id="comments_<%= @picture.id %>">
            <% if @picture.comments %>
                <% @picture.comments.each do |comment| %>
                    <%= render @picture.comments, picture: @picture %>
                <% end %>
            <% end %>
            </div>
        </div>
        <div class="comment_like_form">
            <% if user_signed_in? %>
                <% if !(current_user.liked? @picture) %>

                    <%= link_to like_picture_path(@picture), method: :put, class: "fa" do %>
                        <span class="change-icon">
                        <i class="fa fa-heart-o"></i>
                        <i class="fa fa-heart"></i>
                        </span>
                    <% end %>

                <% else %>

                    <%= link_to dislike_picture_path(@picture), method: :put, class: "fa" do %>
                        <span class="change-icon">
                        <i class="fa fa-heart"></i>
                        <i class="fa fa-heart-o"></i>
                        </span>
                    <% end %>

                <% end %>
                <div class="comment_form">
                    <%= form_for([@picture, @picture.comments.new], remote: true) do |f| %>
                        <h3><%= f.text_field :content, placeholder: 'Add a comment...',id: "comment_content_#{@picture.id}", class: "comment_content" %></h3>
                    <% end %>
                </div>
            <% else %>
                Please log in so you can comment or like this picture. <%= link_to "Log in", unauthenticated_root_path, class: "log_in" %>
            <% end %>
        </div>
    </div>
</div>

app/views/pictures/_picture.html.erb
<div class="picture">
    <%= image_tag @picture.image.url(:medium), :class => "imageShow" %>
    <div id="allBoutImage" class="all">
        <div class="user">
            <%= link_to (image_tag(@picture.user.avatar.url(:mini),:class => "img-circle") + " #{@picture.user.username}"), @picture.user %>
        </div>
        <div class="likes">
            <div class="count">
                <%= @picture.get_likes.size %> likes
            </div>
            <div class="time">
                <%= time_ago_in_words(@picture.created_at) %>
            </div>
        </div>
        <div class="desc_comments">
            <div class="description">
                <%= link_to @picture.user.username, @picture.user %> <%= @picture.description %>
            </div>
            <div class="comments" id="comments_<%= @picture.id %>">
            <% if @picture.comments %>
                <% @picture.comments.each do |comment| %>
                    <%= render @picture.comments, picture: @picture %>
                <% end %>
            <% end %>
            </div>
        </div>
        <div class="comment_like_form">
            <% if user_signed_in? %>
                <% if !(current_user.liked? @picture) %>

                    <%= link_to like_picture_path(@picture), method: :put, class: "fa" do %>
                        <span class="change-icon">
                        <i class="fa fa-heart-o"></i>
                        <i class="fa fa-heart"></i>
                        </span>
                    <% end %>

                <% else %>

                    <%= link_to dislike_picture_path(@picture), method: :put, class: "fa" do %>
                        <span class="change-icon">
                        <i class="fa fa-heart"></i>
                        <i class="fa fa-heart-o"></i>
                        </span>
                    <% end %>

                <% end %>
                <div class="comment_form">
                    <%= form_for([@picture, @picture.comments.new], remote: true) do |f| %>
                        <h3><%= f.text_field :content, placeholder: 'Add a comment...',id: "comment_content_#{@picture.id}", class: "comment_content" %></h3>
                    <% end %>
                </div>
            <% else %>
                Please log in so you can comment or like this picture. <%= link_to "Log in", unauthenticated_root_path, class: "log_in" %>
            <% end %>
        </div>
    </div>
</div>

app/views/pictures/edit.html.erb
<div class="super_skinny_wrapper edit_pic">
    <h2>Edit Pic</h2>
    <div class="center">
        <%= image_tag @picture.image.url(:medium) %>
    </div>
    <%= render 'form' %>
</div>

app/views/pictures/index.html.erb
<div id="index" class="super_skinny_wrapper">
    <% @pictures.each do |picture| %>
        <div class="picture">
            <div class="user clearfix">
                <div class="info">
                    <div class="img_user">
                        <%= link_to (image_tag picture.user.avatar.url(:mini), class: "img-circle"), picture.user %>
                    </div>
                    <div class="name_user">
                        <%= link_to picture.user.username, picture.user %> <br>
                    </div>
                </div>
                <div class="time">
                    <%= time_ago_in_words(picture.created_at) %>
                </div>
            </div>
            <div class="img">
                <%= image_tag picture.image.url(:medium) %>
                <%= link_to picture do %>
                <div class="info_pic" id="grad info_pic_<%= picture.id %>">
                    <h3><i class="fa fa-heart"></i> <%= picture.get_likes.size %> <span><i class="fa fa-comment"></i> <%= picture.comments.count %></span></h3>
                </div>
                <% end %>
            </div>
            <div class="bottom">
                <div class="desc_comments">
                    <div class="description">
                        <%= link_to picture.user.username, picture.user %> <%= picture.description %>
                    </div>
                    <div class="comments" id="comments_<%= picture.id %>">
                    <% if picture.comments %>
                        <% picture.comments.each do |comment| %>
                            <%= render picture.comments, picture: picture %>
                        <% end %>
                    <% end %>
                    </div>
                </div>
                <div class="comment_like_form">
                    <% if !(current_user.liked? picture) %>

                        <%= link_to like_picture_path(picture), method: :put do %>
                            <span class="change-icon">
                            <i class="fa fa-heart-o"></i>
                            <i class="fa fa-heart"></i>
                            </span>
                        <% end %>

                    <% else %>

                        <%= link_to dislike_picture_path(picture), method: :put do %>
                            <span class="change-icon">
                            <i class="fa fa-heart"></i>
                            <i class="fa fa-heart-o"></i>
                            </span>
                        <% end %>

                    <% end %>
                    <div class="comment_form">
                        <%= form_for([picture, picture.comments.new], remote: true) do |f| %>
                            <h3><%= f.text_field :content, placeholder: 'Add a comment...',id: "comment_content_#{picture.id}", class: "comment_content" %></h3>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/pictures/new.html.erb
<div class="super_skinny_wrapper">
    <h2>New Pic</h2>

    <%= render 'form' %>
    
</div>

app/views/pictures/show.html.erb
<div class="wrapper2" id="show">

    <%= render 'picture' %>

</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="wrapper2" id="user_show">
    <div class="header">
        <div class="user_img">
            <%= image_tag @user.avatar.url(:medium), :class => "img-circle" %>
        </div>
        <div class="user_info">
            <div class="username">
                <%= @user.username %>
            </div>
            <div class="desc">
                <div class="name_bio">
                    <span><%= @user.name %></span> <% if @user.bio? %><%= @user.bio %><% end %>
                </div>
                <% if @user.webpage? %>
                <div class="webpage">
                    <a href="<%= @user.webpage %>"><%= @user.webpage %></a>
                </div>
                <% end %>
            </div>
            <div class="counters">
                <div class="pictures">
                    <span><%= @user.pictures.count %></span> pictures
                </div>
                <div class="followers">
                    <span>10</span> followers
                </div>
                <div class="following">
                    <span>43</span> following
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <% @user.pictures.each do |picture| %>
            <div class="picture">
                <%= image_tag picture.image.url(:preview) %>
                <%= link_to picture do %>
                    <div class="info_pic">
                        <h3><i class="fa fa-heart"></i> <%= picture.get_likes.size %> <span><i class="fa fa-comment"></i> <%= picture.comments.count %></span></h3>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>